# Generated by Django 5.1.5 on 2025-02-27 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('mavzu', models.CharField(max_length=200)),
                ('oqituvchi', models.CharField(max_length=100)),
                ('xona', models.CharField(max_length=20)),
                ('boshlanish_vaqti', models.TimeField()),
                ('tugash_vaqti', models.TimeField()),
            ],
            options={
                'verbose_name': 'Dars ',
                'verbose_name_plural': 'Darslar',
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kurs ',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matni', models.TextField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dars')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='dars',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kurs'),
        ),
    ]
