# Generated by Django 5.1.5 on 2025-02-26 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mator_hajmi',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matni', models.TextField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mashina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
