# Generated by Django 5.1.5 on 2025-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default=1234, upload_to='book/photos/'),
            preserve_default=False,
        ),
    ]
