# Generated by Django 5.1.5 on 2025-02-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default=1234, upload_to='author/photos'),
            preserve_default=False,
        ),
    ]
