# Generated by Django 5.1.5 on 2025-04-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ichimliklar',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='burgerlar',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ichimliklar',
            name='liter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lavashlar',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
