# Generated by Django 5.1.5 on 2025-03-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familiya', models.CharField(max_length=50)),
                ('yosh', models.PositiveIntegerField()),
                ('rasm', models.ImageField(upload_to='muallif/rasmlar/')),
            ],
        ),
        migrations.CreateModel(
            name='Nashriyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('manzil', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('janr', models.CharField(max_length=100)),
                ('rasm', models.ImageField(upload_to='kitob/rasmlar/')),
                ('chop_etilgan_sana', models.DateField()),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.muallif')),
                ('nashriyot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nashriyot')),
            ],
        ),
    ]
