# Generated by Django 5.1.5 on 2025-03-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitob',
            options={'verbose_name': 'Kitob ', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='muallif',
            options={'verbose_name': 'Muallif ', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='nashriyot',
            options={'verbose_name': 'Nashriyot ', 'verbose_name_plural': 'Nashriyotlar'},
        ),
        migrations.RenameField(
            model_name='nashriyot',
            old_name='phone_number',
            new_name='telefon',
        ),
        migrations.RemoveField(
            model_name='muallif',
            name='yosh',
        ),
        migrations.AddField(
            model_name='muallif',
            name='tugilgan_sana',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
