# Generated by Django 5.1.5 on 2025-04-18 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_id',
            field=models.ManyToManyField(related_name='teachers', to='app.class'),
        ),
    ]
