# Generated by Django 5.1.5 on 2025-04-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_homework_remove_teacher_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='finished',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='started',
            field=models.DateField(),
        ),
    ]
