# Generated by Django 5.1.5 on 2025-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tarkib',
            field=models.TextField(),
        ),
    ]
