# Generated by Django 5.1.5 on 2025-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_tarkib'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sharh_matni',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
