# Generated by Django 5.1.5 on 2025-04-05 06:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('narxi', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Klass ',
                'verbose_name_plural': 'Klasslar',
            },
        ),
        migrations.CreateModel(
            name='Mehmonxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('yulduzlar_soni', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('narxi', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Mehmonxona ',
                'verbose_name_plural': 'Mehmoxonalar',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('izoh', models.TextField()),
                ('muddati', models.DateField()),
                ('narxi', models.PositiveIntegerField()),
                ('klass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.klass')),
                ('mehmonxona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mehmonxona')),
            ],
            options={
                'verbose_name': 'Travel ',
                'verbose_name_plural': 'Travellar',
            },
        ),
    ]
