# Generated by Django 5.1.5 on 2025-02-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('davlati', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80)),
                ('ot_kuchi', models.IntegerField()),
                ('rangi', models.CharField(max_length=50)),
                ('narxi', models.IntegerField()),
                ('rasmi', models.ImageField(upload_to='car/photo')),
            ],
        ),
    ]
