# Generated by Django 5.1.5 on 2025-03-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='brand',
            new_name='parent',
        ),
    ]
