# Generated by Django 5.1.5 on 2025-02-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dars',
            options={'verbose_name': 'Dars ', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={'verbose_name': 'Kurs ', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AddField(
            model_name='dars',
            name='kurs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.kurs'),
            preserve_default=False,
        ),
    ]
