# Generated by Django 5.1.5 on 2025-02-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dars_options_alter_kurs_options_dars_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dars',
            name='xona',
            field=models.CharField(max_length=20),
        ),
    ]
